### ISSUE TITLE
new PyPI release

### ISSUE THREAD

**Issue by PetrDlouhy** [campaignmonitor/createsend-python#30]
Please create new PyPI release with Python 3 fixes.

**Comment by SpainTrain** [comment]
As well for https://github.com/campaignmonitor/createsend-python/pull/32

**Comment by jdennes** [comment]
I released [4.2.0](https://github.com/campaignmonitor/createsend-python/releases) on [PyPI](https://pypi.python.org/pypi/createsend/) after someone from Campaign Monitor contacted me asking about this. I'm not an active maintainer of this project, so someone from Campaign Monitor should be added as an owner of the package, since they are the maintainers of it.

**Comment by SpainTrain** [comment]
Thanks for taking care of this @jdennes !
